server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}

kafka:
  bootstrap-servers: ${KAFKA_HOST_AND_PORT}
  topics:
    user:
      created:
        name: ${KAFKA_USER_CREATED_TOPIC}
      updated:
        name: ${KAFKA_USER_UPDATED_TOPIC}
      deleted:
        name: ${KAFKA_USER_DELETED_TOPIC}
