version: '3'

services:

  ##############
  ## Local DB ##
  ##############

  local-mongodb-customer:
    image: mongo:5.0
    container_name: local-mongodb-customer
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo/customer:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  ######################
  ## Customer Service ##
  ######################

  customer-service:
    build:
      context: ../services/customer-service
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    container_name: customer-service
    env_file:
      - ./config/common.env
      - ./config/customer-service.env
    depends_on:
      local-mongodb-customer:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
