version: '3'

services:

  ##############
  ## Local DB ##
  ##############
  local-mongodb:
    image: mongo:6.0.4
    container_name: local-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  ##################
  ## Auth Service ##
  ##################
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    container_name: auth-service
    env_file:
      - ./config/common.env
      - ./config/auth-service.env
    depends_on:
      local-mongodb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
