server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}

security:
  oauth2:
    public-key: ${PUBLIC_KEY}

aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET_NAME}

kafka:
  bootstrap-servers: ${KAFKA_HOST_AND_PORT}
  topics:
    user:
      created:
        name: ${KAFKA_USER_CREATED_TOPIC}
      updated:
        name: ${KAFKA_USER_UPDATED_TOPIC}
      deleted:
        name: ${KAFKA_USER_DELETED_TOPIC}
