server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27018
      username: admin
      password: root
      database: admin
  jackson:
    default-property-inclusion: NON_NULL

aws:
  s3:
    accessKey: AKIA6ECJ7J7OQ7QW4CF2
    secretKey: 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
    region: eu-west-1
    bucketName: monkeyshop-customer-media

kafka:
  bootstrap-servers: localhost:9092
  topics:
    user:
      created:
        name: monkeyshop.user.created
      updated:
        name: monkeyshop.user.updated
      deleted:
        name: monkeyshop.user.deleted

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    with-credentials: true
  show-actuator: true

security:
  oauth2:
    public-key: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuObgk+RKEKqQ9EY8gMHL
      1p3Q+OLmq/dQyT4FyafDdPHbB1RXoGM07t4Y+i7Uj6+M4IZOCKrVyEI0BsHv0WEh
      BLN+m5F5/x4oxzDdb4OCUhMrGxPtUQmuqkRSMYqZyD1NHfm+w/3jTiEHeC4PpZxd
      GwXRCwzYjNXV9TFntx8iZnqq8GDuQszyAjfaf1KLVH2lrTPo3ERGt1gKSH5qOfyZ
      ZC0zp89DmPzYSmTWvrzAcclrgvpiy2dk+c+SCKhsMpJqIcREbC7z3kLT1yGYkdx3
      DhyofcSeFws9ibdMbwW7C7PPERnZMGMXOY100i9NpqskK1GrebWuBLwqD8izrMn+
      ewIDAQAB
      -----END PUBLIC KEY-----
